#!/bin/bash -xe
echo "${msg}"
sudo -u splunk /usr/local/bin/aws s3 cp s3://${splunk_license_bucket}/${splunk_license_file} /data/splunk/splunk/etc/
sudo -u splunk /data/splunk/splunk/bin/splunk add licenses /data/splunk/splunk/etc/Splunk.License -auth admin:${splunk_admin_pass}
service splunk restart