# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# Set AWS as the provider and establish creds and default region (alias isn't needed here)
provider aws {
  shared_credentials_file = var.shared_credentials
  profile                 = var.profile
  region                  = var.region
}
variable "shared_credentials" {
  default = "/home/william/.aws/credentials"
}

variable "profile" {
  default = "default"
}

variable "region" {
  default = "ap-southeast-2"
}
